# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/idowe/myProjects/FPGA-image-interpolator/OV5640_VGA/Nexys-A7-100T-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cntl_0_0_1/design_1_cntl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cntl_0_0 || ORIG_REF_NAME==design_1_cntl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov5640_controller_0_0/design_1_ov5640_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov5640_controller_0_0 || ORIG_REF_NAME==design_1_ov5640_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov_5640_caputre_0_0/design_1_ov_5640_caputre_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov_5640_caputre_0_0 || ORIG_REF_NAME==design_1_ov_5640_caputre_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vga_0_0_1/design_1_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vga_0_0 || ORIG_REF_NAME==design_1_vga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0_1/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
