@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 12 16:45:51 +0300 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim BILINEAR_INTERPOLATION_TOP_tb_func_synth -key {Post-Synthesis:sim_1:Functional:BILINEAR_INTERPOLATION_TOP_tb} -tclbatch BILINEAR_INTERPOLATION_TOP_tb.tcl -view C:/Users/idowe/Projects/Digital-Zoom-FPGA/OV7670_VGA/vga_behav.wcfg -view C:/Users/idowe/Projects/Digital-Zoom-FPGA/OV7670_VGA/tb_ovo_7670_capture_behav.wcfg -view C:/Users/idowe/Projects/Digital-Zoom-FPGA/OV7670_VGA/BILINEAR_INTERPOLATION_TOP_tb_behav.wcfg -log simulate.log"
call xsim  BILINEAR_INTERPOLATION_TOP_tb_func_synth -key {Post-Synthesis:sim_1:Functional:BILINEAR_INTERPOLATION_TOP_tb} -tclbatch BILINEAR_INTERPOLATION_TOP_tb.tcl -view C:/Users/idowe/Projects/Digital-Zoom-FPGA/OV7670_VGA/vga_behav.wcfg -view C:/Users/idowe/Projects/Digital-Zoom-FPGA/OV7670_VGA/tb_ovo_7670_capture_behav.wcfg -view C:/Users/idowe/Projects/Digital-Zoom-FPGA/OV7670_VGA/BILINEAR_INTERPOLATION_TOP_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
